
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { briefId, briefData } = await req.json()

    // Generate PDF content
    const pdfContent = generatePDFContent(briefData)
    
    // In a real implementation, you would use a PDF generation library
    // For now, we'll simulate PDF generation
    const pdfBase64 = btoa(pdfContent)

    // Save PDF URL to database (simulated)
    const pdfUrl = `https://storage.googleapis.com/briefs/${briefId}.pdf`

    return new Response(JSON.stringify({ 
      success: true, 
      pdfUrl,
      pdfContent: pdfBase64 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error('Error generating PDF:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})

function generatePDFContent(briefData: any): string {
  const isArabic = briefData.language === 'ar'
  
  return `
${isArabic ? 'موجز المشروع الإبداعي' : 'Creative Project Brief'}
${isArabic ? 'استوديو الفضاء - Of Space Studio' : 'Of Space Studio'}

${isArabic ? 'نوع الخدمة:' : 'Service Type:'} ${briefData.service}
${isArabic ? 'تاريخ الإنشاء:' : 'Created:'} ${briefData.created_at}

${isArabic ? 'تفاصيل المشروع:' : 'Project Details:'}
${Object.entries(briefData.answers).map(([key, value]) => `${key}: ${value}`).join('\n')}

${isArabic ? 'معلومات العميل:' : 'Client Information:'}
${briefData.client_info.name ? `${isArabic ? 'الاسم:' : 'Name:'} ${briefData.client_info.name}` : ''}
${briefData.client_info.email ? `${isArabic ? 'البريد الإلكتروني:' : 'Email:'} ${briefData.client_info.email}` : ''}
${briefData.client_info.phone ? `${isArabic ? 'الهاتف:' : 'Phone:'} ${briefData.client_info.phone}` : ''}

${isArabic ? 'تم إنشاء هذا الموجز بواسطة نجموز 👽' : 'Generated by Nujmooz 👽'}
  `.trim()
}
