
import html2pdf from 'html2pdf.js';
import { supabase } from '@/integrations/supabase/client';

export interface BriefData {
  service: string;
  description: string;
  audience: string;
  style: string;
  budget: string;
  deadline: string;
  language: 'en' | 'ar';
  projectTitle?: string;
  [key: string]: any;
}

export const generateBriefPDF = async (briefData: BriefData, briefId: string): Promise<string | null> => {
  try {
    console.log('Starting PDF generation for brief:', briefId);
    
    // Create HTML content for the PDF
    const htmlContent = createPDFContent(briefData);
    
    // Configure PDF options
    const options = {
      margin: 0.5,
      filename: `project-brief-${briefId}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { 
        scale: 2,
        useCORS: true,
        letterRendering: true
      },
      jsPDF: { 
        unit: 'in', 
        format: 'a4', 
        orientation: 'portrait' 
      }
    };

    console.log('Generating PDF with html2pdf...');
    
    // Generate PDF blob
    const pdfBlob = await html2pdf()
      .set(options)
      .from(htmlContent)
      .outputPdf('blob');
    
    console.log('PDF blob generated, size:', pdfBlob.size);

    // Upload to Supabase storage
    const fileName = `briefs/${briefId}/project-brief-${Date.now()}.pdf`;
    
    console.log('Uploading to Supabase storage:', fileName);
    
    const { data, error } = await supabase.storage
      .from('project_files')
      .upload(fileName, pdfBlob, {
        contentType: 'application/pdf',
        upsert: false
      });

    if (error) {
      console.error('Error uploading PDF:', error);
      return null;
    }

    console.log('PDF uploaded successfully:', data);

    // Get public URL
    const { data: urlData } = supabase.storage
      .from('project_files')
      .getPublicUrl(fileName);

    console.log('Generated public URL:', urlData.publicUrl);

    // Update the project brief with PDF URL
    const { error: updateError } = await supabase
      .from('project_briefs')
      .update({ 
        pdf_url: urlData.publicUrl,
        updated_at: new Date().toISOString()
      })
      .eq('id', briefId);

    if (updateError) {
      console.error('Error updating brief with PDF URL:', updateError);
    }
    
    return urlData.publicUrl;
  } catch (error) {
    console.error('Error generating PDF:', error);
    return null;
  }
};

const createPDFContent = (briefData: BriefData): string => {
  const isArabic = briefData.language === 'ar';
  const projectTitle = briefData.projectTitle || briefData.service || 'Project Brief';
  
  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; direction: ${isArabic ? 'rtl' : 'ltr'}; background: white;">
      
      <!-- Header Section -->
      <div style="text-align: center; margin-bottom: 50px; padding: 30px; background: linear-gradient(135deg, #0A0A0A 0%, #1A1A1A 100%); border-radius: 15px; color: white;">
        <div style="display: flex; align-items: center; justify-content: center; margin-bottom: 20px;">
          <div style="width: 60px; height: 60px; background: linear-gradient(45deg, #7EF5A5, #4AE374); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 15px; font-size: 30px;">
            👽
          </div>
          <div>
            <h1 style="color: #7EF5A5; font-size: 36px; margin: 0; font-weight: bold;">
              ${isArabic ? 'استوديو الفضاء' : 'Of Space Studio'}
            </h1>
          </div>
        </div>
        <p style="color: #ffffff; font-size: 18px; margin: 10px 0;">
          ${isArabic ? 'موجز المشروع الإبداعي الكوني' : 'Cosmic Creative Project Brief'}
        </p>
        <div style="height: 3px; background: linear-gradient(90deg, #7EF5A5 0%, #4AE374 100%); margin: 20px auto; width: 200px; border-radius: 2px;"></div>
        <p style="color: #ffffff; font-size: 14px; opacity: 0.8;">
          ${isArabic ? 'تم إنشاؤه بواسطة نجموز - مساعدك الكوني الإبداعي' : 'Generated by Nujmooz - Your Cosmic Creative Assistant'}
        </p>
      </div>

      <!-- Project Title -->
      <div style="background: #f8f9fa; padding: 40px; border-radius: 15px; margin-bottom: 30px; border: 1px solid #e9ecef;">
        <h2 style="color: #333; margin-bottom: 30px; font-size: 28px; text-align: center; border-bottom: 2px solid #7EF5A5; padding-bottom: 10px;">
          ${projectTitle}
        </h2>
        
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 25px; margin-bottom: 25px;">
          <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #7EF5A5; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h3 style="color: #7EF5A5; margin-bottom: 15px; font-size: 18px; font-weight: 600;">
              ${isArabic ? '🎯 نوع الخدمة' : '🎯 Service Type'}
            </h3>
            <p style="color: #333; font-size: 16px; margin: 0; line-height: 1.5;">${briefData.service || 'Not specified'}</p>
          </div>
          
          <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #4AE374; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h3 style="color: #4AE374; margin-bottom: 15px; font-size: 18px; font-weight: 600;">
              ${isArabic ? '👥 الجمهور المستهدف' : '👥 Target Audience'}
            </h3>
            <p style="color: #333; font-size: 16px; margin: 0; line-height: 1.5;">${briefData.audience || 'Not specified'}</p>
          </div>
          
          <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #7EF5A5; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h3 style="color: #7EF5A5; margin-bottom: 15px; font-size: 18px; font-weight: 600;">
              ${isArabic ? '🎨 الأسلوب المفضل' : '🎨 Preferred Style'}
            </h3>
            <p style="color: #333; font-size: 16px; margin: 0; line-height: 1.5;">${briefData.style || 'Not specified'}</p>
          </div>
          
          <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #4AE374; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
            <h3 style="color: #4AE374; margin-bottom: 15px; font-size: 18px; font-weight: 600;">
              ${isArabic ? '💰 الميزانية' : '💰 Budget'}
            </h3>
            <p style="color: #333; font-size: 16px; margin: 0; line-height: 1.5;">${briefData.budget || 'Not specified'}</p>
          </div>
        </div>
        
        <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #7EF5A5; margin-bottom: 25px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <h3 style="color: #7EF5A5; margin-bottom: 15px; font-size: 18px; font-weight: 600;">
            ${isArabic ? '📝 وصف المشروع' : '📝 Project Description'}
          </h3>
          <p style="color: #333; font-size: 16px; line-height: 1.8; margin: 0;">${briefData.description || 'No description provided'}</p>
        </div>
        
        <div style="background: white; padding: 25px; border-radius: 12px; border-left: 5px solid #4AE374; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
          <h3 style="color: #4AE374; margin-bottom: 15px; font-size: 18px; font-weight: 600;">
            ${isArabic ? '⏰ الجدول الزمني' : '⏰ Timeline'}
          </h3>
          <p style="color: #333; font-size: 16px; margin: 0; line-height: 1.5;">${briefData.deadline || 'Not specified'}</p>
        </div>
      </div>

      <!-- Footer Section -->
      <div style="text-align: center; margin-top: 50px; padding: 30px; background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 15px; border: 1px solid #dee2e6;">
        <div style="margin-bottom: 20px;">
          <div style="width: 40px; height: 40px; background: linear-gradient(45deg, #7EF5A5, #4AE374); border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; margin-bottom: 10px; font-size: 20px;">
            👽
          </div>
        </div>
        <p style="color: #666; font-size: 16px; margin: 10px 0; font-weight: 500;">
          ${isArabic 
            ? 'شكراً لثقتكم في استوديو الفضاء'
            : 'Thank you for trusting Of Space Studio'
          }
        </p>
        <p style="color: #7EF5A5; font-size: 14px; margin: 5px 0; font-weight: 600;">
          ${isArabic ? 'رحلتنا الإبداعية في الفضاء تبدأ الآن! 🚀' : 'Our creative space journey begins now! 🚀'}
        </p>
        <div style="margin-top: 20px; padding-top: 20px; border-top: 1px solid #dee2e6;">
          <p style="color: #999; font-size: 12px; margin: 0;">
            ${isArabic 
              ? `تاريخ الإنشاء: ${new Date().toLocaleDateString('ar-EG')} | استوديو الفضاء للإبداع الرقمي`
              : `Generated on: ${new Date().toLocaleDateString('en-US')} | Of Space Studio - Digital Creative Agency`
            }
          </p>
        </div>
      </div>
    </div>
  `;
};
