// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://mhlvzabsgysciyjaamqo.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obHZ6YWJzZ3lzY2l5amFhbXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTQ0NjQsImV4cCI6MjA2Njc5MDQ2NH0.8aCUZlbFoby8LzUoDwPRYRehNQjy6tY7TcQY6uUHXwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);